### PR TITLE
Remove an extra closing paren

### PR DESCRIPTION
**Pull request by Calvin-LL**

### CODE REVIEW

**Comment by wilbowma** [comment]
Seems to already be fixed in https://github.com/cpsc411/cpsc411-book/tree/2021w2

**Comment by wilbowma** [comment]
Oh, no, this patch is wrong. Removing that paren introduces an unbalanced paren in the example; the removed paren matches the `(patch-instructions ...)`

**Comment by Calvin-LL** [comment]
Oops you're right. I thought I saw an exta 😅. This is what happens when I code while running low on sleep and high on caffeine.

**Comment by wilbowma** [comment]
No worries. FYI, all the examples are running code, so there can't be unbalanced parens in them. And almost all the typeset code is also syntax checked.

**Pull request closed without merging**
